### PR TITLE
fix #1036 scope taggable#tenant method name to #taggable_tenant

### LINKED ISSUE #1036: Models won't save if they already have a `belongs_to :tenant` and `acts_as_taggable_tenant` is used
# How to reproduce:

```ruby

class Tenant < ApplicationRecord
  has_many :users
end

class User < ApplicationRecord
  belongs_to :tenant
  acts_as_taggable_on :tags
  acts_as_taggable_tenant :tenant_id
end

Tenant.create!
```

# Expected behavior

The tenant is created

# Actual behavior

The following error is thrown.

```
NoMethodError - undefined method `marked_for_destruction?' for ID:Integer
```

# Investigation

This is due to: https://github.com/mbleigh/acts-as-taggable-on/pull/1000/files#diff-f3570227aa94bb5887e3cb70c6a69fb30861dbecaa1ee498153371a1e10fc314R217

This line overrides the tenant method and returns an integer instead of an object.
This can be easily fixed by namescoping the method (e.g. `taggable_tenant_id`).

cc @lunaru (BTW, thank you for your work 👍 )

### PR DESCRIPTION
**Pull request by ngouy**
If your taggable model already have a #tenant attribute/method/relationship, it would broke your code.

A small modification is required to scope this (non-documented and normally non directly used) method to the taggable lexical scope to fix the issue

### CODE REVIEW

File: Gemfile [hunk 1]
```diff
@@ -7,5 +7,6 @@ group :local_development do
   gem 'guard-rspec'
   gem 'appraisal'
   gem 'rake'
+  gem 'sqlite3'
```
Comment (ngouy) [inline Gemfile:10]: I added that because it's a requirement when working on the gem

without it:
```
>$ bundle
...
>$ bundle exec rake rspec
```

image

**Comment by ngouy** [comment]
tested on a real project with already existing tenants and it works (from breaking the app to working app)

File: lib/acts_as_taggable_on/taggable/core.rb [hunk 2]
```diff
@@ -214,7 +214,7 @@ def tagging_contexts
       self.class.tag_types.map(&:to_s) + custom_contexts
     end
 
-    def tenant
+    def taggable_tenant
       if self.class.tenant_column
         read_attribute(self.class.tenant_column)
```
Comment (ngouy) [inline lib/acts_as_taggable_on/taggable/core.rb:219]: @lunaru small question: why did we specificly use `#read_attribute`?

If I have a taggable resource that is:
```rb
class MyTaggableModel
  has_one: :tenant, through: :something
  
  acts_as_taggable_on :tags
  acts_as_taggable_tenant :tenant_id
  
  def tenant_id
    something.tenant_id
  end
end
```

It just doesn't works, and that's kinda unfortunate.

File: Gemfile (hunk 1 above)
Comment (seuros) [reply Gemfile:10]: Strange , i never needed to add it. You can use appraisal to run a specific version.

**Comment by seuros** [comment]
Can you bump version 8.1 and update the Changelog ?

**Comment by ngouy** [comment]
@seuros can we also address the #read_attribute issue before please ? really need that on my hand

If we have no specific reason for it's usage I can just use #public_send instead

**Comment by seuros** [comment]
Sure thinh

**Comment by ngouy** [comment]
@seuros we should be good, minor version bump and changelog updated included

**Comment by seuros** [comment]
Awesome work

**Comment by ngouy** [comment]
@seuros when do you think will you release it (no pressure just wondering in terms of planning)

**Comment by seuros** [comment]
Tomorrow max
